define([
  './beat',
  './cuddle',
  './death1',
  './death2',
  './death3',
  './deathwall',
  './defi',
  './eat',
  './feed',
  './idle1',
  './idle2',
  './idle3',
  './idle4',
  './love',
  './music',
  './play',
  './sleep',
  './spreng',
  './suicide',
  './train',
  './training',
], function(
  beat,
  cuddle,
  death1,
  death2,
  death3,
  deathwall,
  defi,
  eat,
  feed,
  idle1,
  idle2,
  idle3,
  idle4,
  love,
  music,
  play,
  sleep,
  spreng,
  suicide,
  train,
  training
){
  return {
    beat: beat,
    cuddle: cuddle,
    death: ["wrandom", [10, death1], [10, death2], [1, death3]],
    death1: death1,
    death2: death2,
    death3: death3,
    deathwall: deathwall,
    defi: defi,
    eat: eat,
    feed: feed,
    idle: ["wrandom", [10, idle1], [10, idle2], [2, idle3]],
    idle1: idle1,
    idle2: idle2,
    idle3: idle3,
    idle4: idle4,
    love: love,
    music: music,
    play: play,
    sleep: sleep,
    spreng: spreng,
    suicide: suicide,
    train: train,
    training: training
  }
});
